FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG API_URL=http://localhost:3000
ENV API_URL=$API_URL

RUN npx nuxt build

EXPOSE 3000

CMD ["node", ".output/server/index.mjs"]
